### ISSUE TITLE
Get this every time i try to install this :) 

### ISSUE THREAD

**Issue by Axachi** [Fortressbeast/AConLinux#2]
Hi thank you  for the script. I am trying this on Solus Linux Budgie. I have tried alot. and found your script after a looooong time banging my head. I get to install. AC Client, Decal. and all is well, but when starting Decal I get the (No DLL) and same if I try to add Thwargle dll ...
Any pointers ?
![Screenshot_20200108_012629](https://user-images.githubusercontent.com/41244180/71940281-00799b80-31b6-11ea-9a15-9b38ede1673f.png)

**Comment by Fortressbeast** [comment]
Sorry for the late reply. I havent looked at this in a while, but it seems there are some new changes in wine that are causing issues. Since I've gotten a few requests I'm going to try to pick it up again and work out the bugs.

**Comment by peetipablo** [comment]
I'm willing to give you a cash bounty if you can get Decal/Thwargle running with the latest version of wine...

**Comment by Fortressbeast** [comment]
Hi Peetipablo,
I have been a bit busy as of late studying for an exam, but once I get that out of the way I plan on getting back to working on this. I appreciate the offer and will keep everyone posted.

**Comment by Axachi** [comment]
Any News on this :P

**Comment by Fortressbeast** [comment]
Nothing of note. I have been really busy, and trying to learn C++ to create a native Linux launcher. I may take some time to look at Thwargle again when I have time off.

**Comment by Fortressbeast** [comment]
New version released. Closing old issues as they should be sorted.
